version: '3'
networks:
  laravel: null
services:
  nginx:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
      args:
        - 'UID=${UID:-1000}'
        - 'GID=${GID:-1000}'
        - 'USER=${USER:-laravel}'
    restart: unless-stopped
    container_name: nginx
    ports:
      - '8000:8000'
    volumes:
      - './src:/var/www/html'
      - '.env:/var/www/html/.env'
    depends_on:
      - php
      - db
    networks:
      - laravel

  php:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
      args:
        - 'UID=${UID:-1000}'
        - 'GID=${GID:-1000}'
        - 'USER=${USER:-laravel}'
    container_name: php
    tty: true
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://dbuser:bigsecret@127.0.0.1/devdb
      DB_CONNECTION: pgsql
      DB_PORT: 5432
      DB_DATABASE: devdb
      DB_USERNAME: devuser
      DB_PASSWORD: devpass
    ports:
      - '80:9000'
    volumes:
      - './src:/var/www/html'
      - '.env:/var/www/html/.env'
    networks:
      - laravel

  db:
    build:
      context: ./docker/db
      dockerfile: Dockerfile
    container_name: db
    restart: always
    volumes:
      - db_data:/var/lib/post/postgresql/data
    environment:
      POSTGRES_PASSWORD: devpass
      POSTGRES_USER: devuser
      POSTGRES_DB: devdb
    ports:
      - "54320:5432"

  composer:
    build:
      context: ./docker/composer
      dockerfile: Dockerfile
      args:
        - 'UID=${UID:-1000}'
        - 'GID=${GID:-1000}'
        - 'USER=${USER:-laravel}'
    container_name: composer
    volumes:
      - './src:/var/www/html'
      - '.env:/var/www/html/.env'
    working_dir: /var/www/html
    depends_on:
      - php
    user: '${USER:-laravel}'
    profiles:
      - composer
    entrypoint:
      - composer
      - '--ignore-platform-reqs'
    networks:
      - laravel

  artisan:
    build:
      context: ./docker/composer
      dockerfile: Dockerfile
      args:
        - 'UID=${UID:-1000}'
        - 'GID=${GID:-1000}'
        - 'USER=${USER:-laravel}'
    container_name: artisan
    volumes:
      - './src:/var/www/html'
      - '.env:/var/www/html/.env'
    working_dir: /var/www/html
    profiles:
      - artisan
    entrypoint:
      - php
      - /var/www/html/artisan
    networks:
      - laravel

  npm:
    image: 'node:alpine'
    container_name: npm
    volumes:
      - './src:/var/www/html'
      - '.env:/var/www/html/.env'
    ports:
      - '3000:3000'
      - '3001:3001'
    working_dir: /var/www/html
    profiles:
      - npm
    entrypoint:
      - npm
    networks:
      - laravel

volumes:
  db_data: