version: '3'

networks:
  laravel:
    driver: bridge

services:
  nginx:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
      args:
        - 'UID=${UID:-1000}'
        - 'GID=${GID:-1000}'
        - 'USER=${USER:-laravel}'
    restart: unless-stopped
    container_name: nginx
    ports:
      - '8000:8000'
    volumes:
      - './src:/var/www/html'
      - '.env:/var/www/html/.env'
    depends_on:
      - php
      - db
    networks:
      - laravel

  php:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
      args:
        - 'UID=${UID:-1000}'
        - 'GID=${GID:-1000}'
        - 'USER=${USER:-laravel}'
    container_name: php
    tty: true
    depends_on:
      - db
    environment:
      DB_CONNECTION: pgsql
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: devdb
      DB_USERNAME: devuser
      DB_PASSWORD: devpass
    ports:
      - '80:9000'
      - '3000:3000'
    volumes:
      - './src:/var/www/html'
      - '.env:/var/www/html/.env'
    networks:
      - laravel

  db:
    image: postgres
    container_name: postgres
    restart: unless-stopped
    tty: true
    ports:
      - "5432:5432"
    volumes:
      - pgsql:/var/lib/post/postgresql/data
    environment:
      - POSTGRES_DB=devdb
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=devpass
    networks:
      - laravel

  composer:
    build:
      context: ./docker/composer
      dockerfile: Dockerfile
      args:
        - 'UID=${UID:-1000}'
        - 'GID=${GID:-1000}'
        - 'USER=${USER:-laravel}'
    container_name: composer
    volumes:
      - './src:/var/www/html'
      - '.env:/var/www/html/.env'
    working_dir: /var/www/html
    depends_on:
      - php
    user: '${USER:-laravel}'
    profiles:
      - composer
    entrypoint:
      - composer
      - '--ignore-platform-reqs'
    networks:
      - laravel

  artisan:
    build:
      context: ./docker/composer
      dockerfile: Dockerfile
      args:
        - 'UID=${UID:-1000}'
        - 'GID=${GID:-1000}'
        - 'USER=${USER:-laravel}'
    container_name: artisan
    volumes:
      - './src:/var/www/html'
      - '.env:/var/www/html/.env'
    working_dir: /var/www/html
    profiles:
      - artisan
    entrypoint:
      - php
      - /var/www/html/artisan
    networks:
      - laravel

  npm:
    image: 'node:alpine'
    container_name: npm
    volumes:
      - './src:/var/www/html'
      - '.env:/var/www/html/.env'
    ports:
      - '3000:3000'
      - '3001:3001'
    working_dir: /var/www/html
    profiles:
      - npm
    entrypoint:
      - npm
    networks:
      - laravel

volumes:
  pgsql: